export const STAGED_INVENTORY_ROW_ROLL_NUMBER_MAX = 30
export const STAGED_INVENTORY_ROW_DYE_LOT_MAX = 30
export const STAGED_INVENTORY_ROW_LOCATION_MAX = 30
export const STAGED_INVENTORY_ROW_NOTE_MAX = 30
