export const INVENTORY_ROLL_NUMBER_MAX = 30
export const INVENTORY_DYE_LOT_MAX = 30
export const INVENTORY_NOTE_MAX = 30
export const INVENTORY_LOCATION_MAX = 30
export const INVENTORY_INTERNAL_NOTES_MAX = 250
