ALTER TABLE "flooring_manufacturer"
ADD COLUMN IF NOT EXISTS "phone" TEXT,
ADD COLUMN IF NOT EXISTS "email" TEXT;

ALTER TABLE "flooring_import_entry"
ADD COLUMN IF NOT EXISTS "importNumber" INTEGER GENERATED BY DEFAULT AS IDENTITY,
ADD COLUMN IF NOT EXISTS "tag" TEXT,
ADD COLUMN IF NOT EXISTS "transportType" TEXT,
ADD COLUMN IF NOT EXISTS "warehouseId" TEXT;

UPDATE "flooring_import_entry"
SET
  "tag" = COALESCE(NULLIF(BTRIM("tag"), ''), NULLIF(BTRIM("importName"), '')),
  "transportType" = COALESCE(NULLIF(BTRIM("transportType"), ''), NULLIF(BTRIM("importType"), ''), 'PURCHASE_ORDER')
WHERE "tag" IS NULL OR "transportType" IS NULL;

ALTER TABLE "flooring_import_entry"
ALTER COLUMN "transportType" SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "flooring_import_entry_importNumber_key" ON "flooring_import_entry"("importNumber");
CREATE INDEX IF NOT EXISTS "flooring_import_entry_warehouseId_idx" ON "flooring_import_entry"("warehouseId");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'flooring_import_entry_warehouseId_fkey'
  ) THEN
    ALTER TABLE "flooring_import_entry"
      ADD CONSTRAINT "flooring_import_entry_warehouseId_fkey"
      FOREIGN KEY ("warehouseId") REFERENCES "flooring_warehouse"("id")
      ON DELETE SET NULL
      ON UPDATE CASCADE;
  END IF;
END $$;

ALTER TABLE "flooring_inventory"
ADD COLUMN IF NOT EXISTS "importEntryId" TEXT,
ADD COLUMN IF NOT EXISTS "cost" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "freight" DECIMAL(10,2);

ALTER TABLE "flooring_inventory"
ALTER COLUMN "itemNumber" TYPE TEXT USING "itemNumber"::TEXT,
ALTER COLUMN "dyeLot" TYPE TEXT USING "dyeLot"::TEXT;

CREATE INDEX IF NOT EXISTS "flooring_inventory_importEntryId_idx" ON "flooring_inventory"("importEntryId");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'flooring_inventory_importEntryId_fkey'
  ) THEN
    ALTER TABLE "flooring_inventory"
      ADD CONSTRAINT "flooring_inventory_importEntryId_fkey"
      FOREIGN KEY ("importEntryId") REFERENCES "flooring_import_entry"("id")
      ON DELETE SET NULL
      ON UPDATE CASCADE;
  END IF;
END $$;

DROP INDEX IF EXISTS "flooring_inventory_locationId_itemNumber_key";
CREATE UNIQUE INDEX IF NOT EXISTS "flooring_inventory_locationId_itemNumber_key" ON "flooring_inventory"("locationId", "itemNumber");

ALTER TABLE "flooring_import_entry"
DROP COLUMN IF EXISTS "importName",
DROP COLUMN IF EXISTS "importType",
DROP COLUMN IF EXISTS "source";
