-- Enable pg_trgm so GIN indexes declared in schema.prisma can use
-- `gin_trgm_ops`. The indexes themselves (btree composites + GIN trgm) are
-- generated by Prisma into a subsequent migration when `db:migrate:dev` runs.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
