export type InventoryAdjustmentDomainErrorCode =
  | "INVENTORY_ADJUSTMENT_ARITHMETIC_MISMATCH"
  | "INVENTORY_ADJUSTMENT_INVENTORY_NOT_IMPORTED"
  | "INVENTORY_ADJUSTMENT_EXCEEDS_STARTING_BALANCE"
  | "INVENTORY_ADJUSTMENT_DELETE_NOT_MOST_RECENT"
  | "INVENTORY_ADJUSTMENT_INVALID_TRANSITION"
  | "INVENTORY_ADJUSTMENT_LINKAGE_ASYMMETRY"
  | "INVENTORY_ADJUSTMENT_PENDING_INPUT_NOT_ALLOWED"
  | "INVENTORY_ADJUSTMENT_BATCH_INELIGIBLE"
  | "INVENTORY_ADJUSTMENT_PENDING_SAVE_VALIDATION_FAILED"
  | "INVENTORY_ADJUSTMENT_NET_DEDUCTED_EXCEEDS_STARTING_STOCK"
  | "INVENTORY_ADJUSTMENT_FINAL_SEQUENCE_INVALID"
  | "INVENTORY_ADJUSTMENT_STALE_UPDATED_AT"
  | "INVENTORY_ADJUSTMENT_LINK_NOT_ALLOWED"
  | "INVENTORY_ADJUSTMENT_LINK_SCOPE_MISMATCH"
  | "INVENTORY_ADJUSTMENT_INCREASE_REQUIRES_NO_WORK_ORDER"
  | "INVENTORY_ADJUSTMENT_INCREASE_REQUIRES_NO_WASTE"

export class InventoryAdjustmentDomainError extends Error {
  readonly code: InventoryAdjustmentDomainErrorCode
  readonly detail?: Record<string, unknown>

  constructor(code: InventoryAdjustmentDomainErrorCode, detail?: Record<string, unknown>) {
    super(code)
    this.name = "InventoryAdjustmentDomainError"
    this.code = code
    this.detail = detail
  }
}
