export const INVENTORY_ADJUSTMENT_PAGE_SIZE = 15
export const INVENTORY_ADJUSTMENT_MAX_PAGE_SIZE = 50

export const INVENTORY_ADJUSTMENTS_LIST_PAGE_SIZE = 25
export const INVENTORY_ADJUSTMENTS_LIST_MAX_PAGE_SIZE = 100
