export const SEEDED_CATEGORIES = [
  { name: "Plank" },
  { name: "Carpet Tile" },
  { name: "Covebase" },
  { name: "Pad" },
  { name: "Adhesive" },
  { name: "Baseboard" },
  { name: "Carpet" },
  { name: "Kilz" },
  { name: "Luan" },
  { name: "Metals" },
  { name: "Moisture Barrier" },
  { name: "Patch" },
  { name: "Plywood" },
  { name: "Primer" },
  { name: "Scent Stop" },
  { name: "Shoe Molding" },
  { name: "Trim" },
  { name: "VCT" },
  { name: "Vinyl Sheet" },
  { name: "Wax Ring" },
  { name: "Ceramic Tile" },
  { name: "Stair Treads" },
  { name: "Rubber Transition" },
  { name: "Rock/Stone" },
] as const

export type SeededCategory = (typeof SEEDED_CATEGORIES)[number]
