export const SEEDED_CATEGORIES = [
  {
    slug: "vinyl-plank",
    name: "Plank",
    sendUnitSlug: "square-feet",
    stockUnitSlug: "boxes",
    itemCoverageUnitSlug: "square-feet",
  },
  {
    slug: "carpet-tile",
    name: "Carpet Tile",
    sendUnitSlug: "square-yard",
    stockUnitSlug: "boxes",
    itemCoverageUnitSlug: "square-yard",
  },
  {
    slug: "covebase",
    name: "Covebase",
    sendUnitSlug: "linear-feet",
    stockUnitSlug: "boxes",
    itemCoverageUnitSlug: "linear-feet",
  },
  {
    slug: "pad",
    name: "Pad",
    sendUnitSlug: "square-yard",
    stockUnitSlug: "rolls",
    itemCoverageUnitSlug: "square-yard",
  },
  {
    slug: "adhesive",
    name: "Adhesive",
    sendUnitSlug: "buckets",
    stockUnitSlug: "buckets",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "baseboard",
    name: "Baseboard",
    sendUnitSlug: "pieces",
    stockUnitSlug: "pieces",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "carpet",
    name: "Carpet",
    sendUnitSlug: "linear-feet",
    stockUnitSlug: "linear-feet",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "kilz",
    name: "Kilz",
    sendUnitSlug: "units",
    stockUnitSlug: "units",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "luan",
    name: "Luan",
    sendUnitSlug: "sheets",
    stockUnitSlug: "sheets",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "metals",
    name: "Metals",
    sendUnitSlug: "pieces",
    stockUnitSlug: "pieces",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "moisture-barrier",
    name: "Moisture Barrier",
    sendUnitSlug: "units",
    stockUnitSlug: "units",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "patch",
    name: "Patch",
    sendUnitSlug: "bags",
    stockUnitSlug: "bags",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "plywood",
    name: "Plywood",
    sendUnitSlug: "sheets",
    stockUnitSlug: "sheets",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "primer",
    name: "Primer",
    sendUnitSlug: "units",
    stockUnitSlug: "units",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "scent-stop",
    name: "Scent Stop",
    sendUnitSlug: "units",
    stockUnitSlug: "units",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "shoe-molding",
    name: "Shoe Molding",
    sendUnitSlug: "pieces",
    stockUnitSlug: "pieces",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "trim",
    name: "Trim",
    sendUnitSlug: "pieces",
    stockUnitSlug: "pieces",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "vct",
    name: "VCT",
    sendUnitSlug: "boxes",
    stockUnitSlug: "boxes",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "vinyl-sheet",
    name: "Vinyl Sheet",
    sendUnitSlug: "linear-feet",
    stockUnitSlug: "linear-feet",
    itemCoverageUnitSlug: null,
  },
  {
    slug: "wax-ring",
    name: "Wax Ring",
    sendUnitSlug: "boxes",
    stockUnitSlug: "boxes",
    itemCoverageUnitSlug: null,
  },
] as const

export type SeededCategory = (typeof SEEDED_CATEGORIES)[number]
