ALTER TABLE "UserTablePreference"
ADD COLUMN IF NOT EXISTS "isAscendingSort" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "UserTablePreference"
ADD COLUMN IF NOT EXISTS "isGroupingEnabled" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "UserTablePreference"
ADD COLUMN IF NOT EXISTS "groupByKeys" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "UserTablePreference"
ADD COLUMN IF NOT EXISTS "filtersJson" JSONB;
