name: Graphs CI
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types:
      - graphs
  workflow_dispatch: {}

jobs:
  graphs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate graphs
        uses: upptime/uptime-monitor@v1
        with:
          command: "graphs"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
