name: Summary CI
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types:
      - summary
  workflow_dispatch: {}

jobs:
  summary:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Update summary
        uses: upptime/uptime-monitor-action@v1
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
